<?php if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_category-details',
        'title' => 'Category Details',
        'fields' => array (
            array (
                'key' => 'field_57c6d1855d6c9',
                'label' => 'Category Page Layout',
                'name' => 'category_page_layout',
                'type' => 'select',
                'instructions' => 'You can set category page layout.',
                'choices' => array (
                    'style-1' => 'Top Meta + Feature Image',
                    'style-2' => 'Top Feature Image + Meta',
                    'style-3' => 'Left Feature Image + Right Meta',
                ),
                'default_value' => 'style-1',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_57c6d21efc86a',
                'label' => 'Category Page Sidebar',
                'name' => 'category_page_sidebar',
                'type' => 'select',
                'instructions' => 'Set category page sidebar position.',
                'choices' => array (
                    'hide' => 'Hide',
                    'left' => 'Left',
                    'right' => 'Right',
                ),
                'default_value' => 'hide',
                'allow_null' => 0,
                'multiple' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'ef_taxonomy',
                    'operator' => '==',
                    'value' => 'category',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_contact-details',
        'title' => 'Contact Details',
        'fields' => array (
            array (
                'key' => 'field_57fdcc1cda46c',
                'label' => 'Form Heading',
                'name' => 'form_heading',
                'type' => 'text',
                'default_value' => 'PLEASE FILL-UP FEW DETAILS',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57fdcc2ada46d',
                'label' => 'Form Shortcode',
                'name' => 'form_shortcode',
                'type' => 'text',
                'instructions' => 'Input contact form 7 shortcode, recommended.',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57fdcc4eda46e',
                'label' => 'Address Heading',
                'name' => 'address_heading',
                'type' => 'text',
                'default_value' => 'OUR ADDRESS',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57fdcc6ada46f',
                'label' => 'Contact Address',
                'name' => 'contact_address',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_57fdcc81da470',
                'label' => 'Contact Phone',
                'name' => 'contact_phone',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57fdcc8cda471',
                'label' => 'Contact Email',
                'name' => 'contact_email',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57fdcc9ada472',
                'label' => 'Contact Extra Info',
                'name' => 'contact_extra_info',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_57fdccc54e5ca',
                'label' => 'Map Latitude',
                'name' => 'map_latitude',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57fdcccf4e5cb',
                'label' => 'Map Longitude',
                'name' => 'map_longitude',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57fdccea4e5cd',
                'label' => 'Map Zoom Level',
                'name' => 'map_zoom_level',
                'type' => 'number',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 1,
                'max' => '',
                'step' => '',
            ),
            array (
                'key' => 'field_57fdccfe4e5ce',
                'label' => 'Map Title',
                'name' => 'map_title',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57fdccdc4e5cc',
                'label' => 'Map Marker',
                'name' => 'map_marker',
                'type' => 'image',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'pge-contact.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'custom_fields',
                3 => 'discussion',
                4 => 'comments',
                5 => 'revisions',
                6 => 'slug',
                7 => 'author',
                8 => 'format',
                9 => 'featured_image',
                10 => 'categories',
                11 => 'tags',
                12 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_ecoshop-details',
        'title' => 'Ecoshop Details',
        'fields' => array (
            array (
                'key' => 'field_57fcc47ac4c8b',
                'label' => 'Delivery Information',
                'name' => 'delivery_information',
                'type' => 'textarea',
                'instructions' => 'Input delivery information for your product.',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 8,
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_57fcc4b3a94be',
                'label' => 'Delivery Information String',
                'name' => 'delivery_information_string',
                'type' => 'text',
                'instructions' => 'You can override default string value here.',
                'default_value' => 'DELIVERY INFORMATION',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57fcc5185c056',
                'label' => 'Double Image',
                'name' => 'double_image',
                'type' => 'image',
                'instructions' => 'You can set second image for your product which will be displayed on hover.',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'product',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'side',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_page-details',
        'title' => 'Page Details',
        'fields' => array (
            array (
                'key' => 'field_57fe397a70b9d',
                'label' => 'Page Layout',
                'name' => 'page_layout',
                'type' => 'select',
                'instructions' => 'You can set page layout, grid or full width without any container holding it.',
                'choices' => array (
                    'container' => 'Container',
                    'full-width' => 'Full Width (VC Recommended)',
                ),
                'default_value' => 'container',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_57fe3a46e9cf2',
                'label' => 'Hide Page Title',
                'name' => 'hide_page_title',
                'type' => 'select',
                'instructions' => 'You can hide page title.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_57fe397a70b9d',
                            'operator' => '==',
                            'value' => 'container',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'choices' => array (
                    'yes' => 'Yes',
                    'no' => 'No',
                ),
                'default_value' => 'no',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_57fe3a1ede2a4',
                'label' => 'Page Classes',
                'name' => 'page_classes',
                'type' => 'text',
                'instructions' => 'You can input page classes separating by space.',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'default',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'side',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_page-headers',
        'title' => 'Page Headers',
        'fields' => array (
            array (
                'key' => 'field_580386e74137d',
                'label' => 'Select Page Header Type',
                'name' => 'select_page_header_type',
                'type' => 'select',
                'choices' => array (
                    'header-plain' => 'Header Plain',
                    'header-plain-transparent' => 'Header Plain (Transparent)',
                    'header-hamburg' => 'Header Hamburg',
                    'header-top-bar' => 'Header Top Bar',
                    'header-full-width' => 'Header Full Width',
                ),
                'default_value' => 'header-plain',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_5803878f1c6a9',
                'label' => 'Banner Type',
                'name' => 'banner_type',
                'type' => 'select',
                'instructions' => 'You can choose your banner options.',
                'choices' => array (
                    'hide' => 'Hide',
                    'parallax-breadcrumb' => 'Parallax Breadcrumb',
                    'parallax-feature-product' => 'Parallax Feature Product',
                    'slider-revolution' => 'Slider Revolution',
                ),
                'default_value' => 'hide',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_58039bd057783',
                'label' => 'Main Heading',
                'name' => 'main_heading_bread',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_5803878f1c6a9',
                            'operator' => '==',
                            'value' => 'parallax-breadcrumb',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_58039bef57784',
                'label' => 'Small Description',
                'name' => 'small_description_bread',
                'type' => 'textarea',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_5803878f1c6a9',
                            'operator' => '==',
                            'value' => 'parallax-breadcrumb',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_58039c1f57785',
                'label' => 'Background Image',
                'name' => 'background_image_bread',
                'type' => 'image',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_5803878f1c6a9',
                            'operator' => '==',
                            'value' => 'parallax-breadcrumb',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_58045548652ab',
                'label' => 'Currency Symbol',
                'name' => 'currency_symbol_feature',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_5803878f1c6a9',
                            'operator' => '==',
                            'value' => 'parallax-feature-product',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_58045557652ac',
                'label' => 'Price',
                'name' => 'price_feature',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_5803878f1c6a9',
                            'operator' => '==',
                            'value' => 'parallax-feature-product',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_58045569652ad',
                'label' => 'Main Heading',
                'name' => 'main_heading_feature',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_5803878f1c6a9',
                            'operator' => '==',
                            'value' => 'parallax-feature-product',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_58045574652ae',
                'label' => 'Feature Heading',
                'name' => 'feature_heading_feature',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_5803878f1c6a9',
                            'operator' => '==',
                            'value' => 'parallax-feature-product',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_58045584652af',
                'label' => 'Shop Link',
                'name' => 'shop_link_feature',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_5803878f1c6a9',
                            'operator' => '==',
                            'value' => 'parallax-feature-product',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_580455e6dbf00',
                'label' => 'Background Image',
                'name' => 'background_image_feature',
                'type' => 'image',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_5803878f1c6a9',
                            'operator' => '==',
                            'value' => 'parallax-feature-product',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_58045622a06f3',
                'label' => 'Slider Revolution Alias',
                'name' => 'slider_revolution_alias',
                'type' => 'text',
                'instructions' => 'Input slider revolution alias only not complete shortcode.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_5803878f1c6a9',
                            'operator' => '==',
                            'value' => 'slider-revolution',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'default',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'pge-contact.php',
                    'order_no' => 0,
                    'group_no' => 1,
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                    'order_no' => 0,
                    'group_no' => 2,
                ),
            ),
            array (
                array (
                    'param' => 'ef_taxonomy',
                    'operator' => '==',
                    'value' => 'category',
                    'order_no' => 0,
                    'group_no' => 3,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_post-user-details',
        'title' => 'Post User Details',
        'fields' => array (
            array (
                'key' => 'field_57cd409bfffe4',
                'label' => 'Blog Author',
                'name' => 'blog_author_xx',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57cd40b7fffe5',
                'label' => 'Author Designation',
                'name' => 'author_designation_xx',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57cd40c8fffe6',
                'label' => 'Author Description',
                'name' => 'author_description_xx',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array (
                'key' => 'field_57cd40dffffe7',
                'label' => 'Facebook',
                'name' => 'facebook_xx',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57cd40e7fffe8',
                'label' => 'Twitter',
                'name' => 'twitter_xx',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57cd40effffe9',
                'label' => 'Linkedin',
                'name' => 'linkedin_xx',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57cd40f7fffea',
                'label' => 'Pinterest',
                'name' => 'pinterest_xx',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57cd40fefffeb',
                'label' => 'Instagram',
                'name' => 'instagram_xx',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_57cd4113fffec',
                'label' => 'Email',
                'name' => 'email_xx',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'ef_user',
                    'operator' => '==',
                    'value' => 'all',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_testimonial-details',
        'title' => 'Testimonial Details',
        'fields' => array (
            array (
                'key' => 'field_57ffaa7886217',
                'label' => 'Testimonial Text',
                'name' => 'testimonial_text',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_57ffaa8786218',
                'label' => 'Testimonial Author',
                'name' => 'testimonial_author',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'ecoshop-testimonials',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'permalink',
                1 => 'the_content',
                2 => 'excerpt',
                3 => 'custom_fields',
                4 => 'discussion',
                5 => 'comments',
                6 => 'revisions',
                7 => 'slug',
                8 => 'author',
                9 => 'format',
                10 => 'featured_image',
                11 => 'categories',
                12 => 'tags',
                13 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_page-footer-details',
        'title' => 'Page Footer Details',
        'fields' => array (
            array (
                'key' => 'field_5806fbfa07394',
                'label' => 'Message',
                'name' => '',
                'type' => 'message',
                'message' => 'For general pages like search, 404, shop; see theme options.',
            ),
            array (
                'key' => 'field_5806fc5d0d2ab',
                'label' => 'Hide About Section',
                'name' => 'hide_about_section',
                'type' => 'select',
                'choices' => array (
                    'yes' => 'Yes',
                    'no' => 'No',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_5806fc930d2ac',
                'label' => 'About Shop Heading',
                'name' => 'about_shop_heading',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5806fca40d2ad',
                'label' => 'About Shop Description',
                'name' => 'about_shop_description',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5806fcb80d2ae',
                'label' => 'Hide Newsletter Section',
                'name' => 'hide_newsletter_section',
                'type' => 'select',
                'choices' => array (
                    'yes' => 'Yes',
                    'no' => 'No',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_5806fcd80d2af',
                'label' => 'Newsletter Style',
                'name' => 'newsletter_style',
                'type' => 'select',
                'choices' => array (
                    'dark' => 'Dark',
                    'color' => 'Color',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_5806fcfe0d2b0',
                'label' => 'Newsletter Heading',
                'name' => 'newsletter_heading',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5806fd0e0d2b1',
                'label' => 'Newsletter Description',
                'name' => 'newsletter_description',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5806fd200d2b2',
                'label' => 'Newsletter Shortcode',
                'name' => 'newsletter_shortcode',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 1,
                ),
            ),
            array (
                array (
                    'param' => 'ef_taxonomy',
                    'operator' => '==',
                    'value' => 'category',
                    'order_no' => 0,
                    'group_no' => 2,
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'product',
                    'order_no' => 0,
                    'group_no' => 3,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 10,
    ));
} ?>